from src.styles import *
from src.read_ini import config
from src.events import AssEvents


_VIDEO_PATH = config.get("File Path", "VIDEO_PATH")
_video_file_name = config.get("Info", "video_file_name")


script_info = "\
[Script Info]\n\
; Script generated by Aegisub 3.2.2\n\
; http://www.aegisub.org/\n\
Title: WORLD DAI STAR STORY\n\
ScriptType: v4.00+\n\
WrapStyle: 0\n\
YCbCr Matrix: TV.601\n\
PlayResX: 1920\n\
PlayResY: 1080\n\
"

garbage = f"\
[Aegisub Project Garbage]\n\
Last Style Storage: Default\n\
Audio File: ../{_VIDEO_PATH}/{_video_file_name}\n\
Video File: ../{_VIDEO_PATH}/{_video_file_name}\n\
Video AR Mode: \n\
Video AR Value: \n\
Video Zoom Percent: \n\
Scroll Position: \n\
Active Line: \n\
Video Position: \n\
"

styles = f"\
[V4+ Styles]\n\
{AssStyles.echo_format()}\n\
{style_1.echo()}\n\
{style_2.echo()}\n\
{style_3.echo()}\n\
{style_4.echo()}\n\
{style_5.echo()}\n\
"

events = f"\
[Events]\n\
{AssEvents.echo_format()}\n\
"
